version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=${MONGO_URL}
volumes:
  mongodb_data:


      